app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.choice , name="choice"),
    path('<int:question_id>/detail/', views.detail, name='detail'),
    path('home/', views.Home.as_view(), name='home'),
    #path('teacher', views.teacher , name="teacher"),
]

system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
]

app/models.py
from django.db import models

# Create your models here.

class QUEST(models.Model):
    question_id = models.AutoField(primary_key=True)
    question_text = models.CharField(max_length=200)

class IO(models.Model):
    question = models.ForeignKey(QUEST, to_field="question_id", on_delete=models.CASCADE) #親のオブジェクトが削除されたら同じidのオブジェクトを削除する
    io_id = models.IntegerField(default=0)
    input_text = models.CharField(max_length=200)
    output_text = models.CharField(max_length=200)

app/forms.py
from django import forms

class EditorForm(forms.Form):
    """エディタ部分となるフォーム."""
    code = forms.CharField(
        widget=forms.Textarea,
    )

app/views.py
from django.shortcuts import render
from .models import QUEST , IO
from django.http import Http404
from django.views import generic
import datetime , os , subprocess
from .forms import EditorForm
from django.urls import reverse_lazy
from django.conf import settings

file_dir = os.path.join(settings.BASE_DIR, 'history') #パスの統合(プログラムを格納するディレクトリへの絶対パス)
docker_cmd = 'docker run -i --rm --name my-running-script -v {}:/usr/src/myapp -w /usr/src/myapp python:3.7 python {}' #{}は置換フィールド29行目format()で置換


def choice(request):
    question_list = QUEST.objects.order_by('question_id')
    context = {'question_list': question_list}
    return render(request, 'choice.html', context)

def detail(request,question_id):
    try:
        question = QUEST.objects.get(pk=question_id)
    except QUEST.DoesNotExist:
        raise Http404("QUEST does not exist")
    return render(request, 'detail.html', {'question': question})

class Home(generic.FormView): #FormView : POST
    template_name = 'home.html'
    form_class = EditorForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        """送信ボタンでよびだされる."""
        code = form.cleaned_data['code']
        output = start_docker(code)
        context = self.get_context_data(form=form, output=output)
        return self.render_to_response(context) #ページの更新

def start_docker(code):
    """dockerコンテナ内でPythonコードを実行する."""
    # historyディレクトリ内に、2019-07-29T22:58:24.1111.py のようなファイルを作り、中身は入力したコード
    file_name = '{}.py'.format(datetime.datetime.now().isoformat()) #.isoformat() == 日付を ISO 8601 書式の YYYY-MM-DDの文字列で返す
    file_path = os.path.join(file_dir, file_name) #保存するプログラムファイルのパス
    with open(file_path, 'w', encoding='utf-8') as file: #→file=open(...)
        file.write(code) #引数として受け取ったコードを書き込む

    '''with A as B:
        処理X
        
        開始・終了の処理が必要なAをB=Aで開始して処理Xをした後に終了する'''
    for _ in range(10):
        cmd = docker_cmd.format(file_dir, file_name) #format関数で{}に適切な値を入れコマンドを完成させる
        ret = subprocess.run( #subprocess 他のアプリを呼び出す　標準ライブラリの1つ
            cmd, timeout=15, shell=True, #timeout[s]:タイムアウト時間[秒]　　shell:＝trueで標準shellを使用
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT  #stdout:標準出力 stderr:標準エラー
        )
    return ret.stdout.decode()

app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>オンラインPython実行環境</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <style>
        html, body, form {
            height: 100vh;
        }
        #editor {
            height: 60vh;
        }
        #commandline {
          height:10vh;
        }
        #output {
            height: 30vh;
        }

        #output button {
            height: 10vh;
        }
        #output pre {
            height: 90%;
            overflow: scroll;
        }

      #all {
        display: flex;
      }
      #left {
        flex-grow: 1;
      }
      #center {
        flex-grow: 1;
      }
      #right {
        flex-grow: 1;
      }
    </style>
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <!-- Ace Editor settings -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ace.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ext-language_tools.js"></script>
    <script src="https://cloud9ide.github.io/emmet-core/emmet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ext-emmet.js"></script>
    <script>
        var langTools = ace.require("ace/ext/language_tools");
        var editor = ace.edit("code");
        var textarea = $('textarea[name="code"]').hide();
        editor.getSession().setValue(textarea.val());
        editor.getSession().on('change', function(){
          textarea.val(editor.getSession().getValue());
        });
        editor.$blockScrolling = Infinity;
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true,
            enableEmmet: true,
        });
        editor.setTheme("ace/theme/monokai");
        editor.getSession().setMode("ace/mode/python");
        editor.setFontSize(20);
    </script>
  </body>
</html>

app/templates/choice.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'detail' question.question_id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No question_text are undefind</p>
{% endif %}

app/templates/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'home'%}" method="post">
{% csrf_token %}
{% for test in question.io_set.all %}
    {% if forloop.counter <= 3 %}
    <label>
        <label>
            <h3>入力例{{forloop.counter}}</h3>
            <h4>{{ test.input_text }}</h4>
        </label>
        <label>
            <h3>出力例{{forloop.counter}}</h3>
            <h4>{{ test.output_text }}</h4>
        </label>
    </label>
    {% endif %}
{% endfor %}
<input type="submit" value="問題を解く" />
</form>

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<form action='' method="POST">
  <div id="all">
    <div id="left">
        <h1>問題文</h1>
        <h3>　問題文の表示</h3>
        <label>
            <label>入力例1<br>　OOOOO</label><br/>
            <label>出力例1<br>　XXXXX</label><br/>
            <label>入力例2<br>　OOOOO</label><br/>
            <label>出力例2<br>　XXXXX</label><br/>
            <label>入力例3<br>　OOOOO</label><br/>
            <label>出力例3<br>　XXXXX</label><br/>
        </label>
    </div>
    
    <div id="center">
        <!-- コード入力エリア -->
        <div id="editor">
            {{ form.code }}
            <div id="code" class="h-100"></div>
        </div>
        <div id="commandline">
            <h3>引数の入力<h3>
            <button type="submit" class="btn btn-warning">実行</button>
        </div>
        <!-- 出力表示エリア -->
        <div id="output" class="bg-inverse">
            <pre class="text-white">{{ output }}</pre>
             {% csrf_token %}
        </div>   
    </div>
    <div id="right">
        <h1>正誤判定</h1>
    </div>
  </div>

</form>

{% endblock %}

app/templates/home2.html
{% extends "app/base.html" %}

{% block content %}
<form action='' method="POST">
        <!-- コード入力エリア -->
        <div id="editor">
            {{ form.code }}
            <div id="code" class="h-100"></div>
        </div>
        <!--<div id="commandline">
            <h3>引数の入力<h3>
            <button type="submit" class="btn btn-warning">実行</button>
        </div>
        -->
        <button type="submit" class="btn btn-warning">実行</button>
        <!-- 出力表示エリア -->
        <div id="output" class="bg-inverse">
            <pre class="text-white">{{ output }}</pre>
             {% csrf_token %}
        </div>   

</form>

{% endblock %}

app/templates/index.html
<h1>hello<h1>